(define (problem blocks-6-w2)
  (:domain BLOCKS)
  (:objects A B C D E F)
  (:init
    (CLEAR F)
    (ONTABLE F)
    (HANDEMPTY)
    (CLEAR A)
    (ON A B)
    (ON B D)
    (ON D E)
    (ONTABLE E)
    (ONTABLE C)
  )
  (:goal (AND (ON E F)))
)
