(define (problem blocks-5-w1)
  (:domain BLOCKS)
  (:objects A B C D E)
  (:init
    (HANDEMPTY)
    (CLEAR A)
    (ON A B)
    (ON B C)
    (ON C D)
    (ON D E)
    (ONTABLE E)
  )
  (:goal (AND (CLEAR D)))
)
