image: ubuntu:22.04

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

precommit:
  image: python:3.12
  script:
    - python -m ensurepip --upgrade
    - python -m pip install --upgrade pip setuptools wheel
    - python --version ; pip --version
    - apt-get update && apt install -y --no-install-recommends git
    - pip install isort black pre-commit
    - pre-commit autoupdate -j 4
    - pre-commit run --all-files

pytest:
  stage: test
  parallel:
    matrix:
      - PYTHON_IMAGE: python:3.9
      - PYTHON_IMAGE: python:3.10
      - PYTHON_IMAGE: python:3.11
      - PYTHON_IMAGE: python:3.12
  image: $PYTHON_IMAGE
  script:
    - python -m pip install --upgrade pip setuptools wheel
    - python --version && pip --version  # For debugging
    - pip install '.[dev]'
    - python -m pytest
